// steps/selectTopic.js

// The list of topics (Cleaned: no numbers)
const topicsList = [
    "Why Consistency Matters More Than Creativity",
    "What Happens When You Disappear From Social Media",
    "The Hidden Cost of Starting Over Every Month",
    "Why Posting Feels Harder Than It Should",
    "When Life Gets Busy and Content Stops",
    "The Difference Between Being Visible and Being Loud",
    "Why Your Product Doesn’t Need New Angles Every Week",
    "How Inconsistency Quietly Hurts Sales",
    "Why Motivation Isn’t a Content Strategy",
    "The Stress of Remembering to Post",
    "Why Simple Repetition Builds Trust",
    "When Social Media Becomes Another To-Do List",
    "The Exhaustion of Always Rewriting the Same Message",
    "Why Boring Content Still Works",
    "How Consistency Creates Familiarity",
    "Why Falling Off Social Media Is So Common",
    "The Problem With Posting Only When You Have Time",
    "Why You Don’t Need to Go Viral to Be Remembered",
    "When Content Feels Like a Distraction From Real Work",
    "The Emotional Weight of Inconsistent Posting",
    "Why Systems Work Better Than Willpower",
    "The Relief of Knowing Your Posts Are Handled",
    "How Missed Weeks Add Up Over Time",
    "Why Selling the Same Thing Repeatedly Is Normal",
    "When Social Media Feels Like Background Noise",
    "The Difference Between Effort and Structure",
    "Why Most People Don’t Hate Social Media — They Hate Managing It",
    "How Visibility Fades Faster Than You Think",
    "Why Posting Sporadically Feels So Discouraging",
    "The Calm That Comes From Set-It-And-Forget-It Content",
    "Why You Don’t Need Fresh Ideas Every Day",
    "How Consistency Supports Trust Without Pressure",
    "When Content Steals Energy From Your Actual Work",
    "The Problem With Relying on Inspiration",
    "Why Repetition Is How People Remember You",
    "How Skipped Weeks Affect Momentum",
    "Why Content Should Fit Into Your Life — Not Run It",
    "The Stress of Wondering If You’ve Posted Enough",
    "Why Staying Visible Doesn’t Have to Be Hard",
    "The Difference Between Active and Consistent",
    "How Simple Posting Systems Reduce Mental Load",
    "Why Most Small Sellers Struggle With Consistency",
    "When Posting Feels Like One More Thing to Manage",
    "Why Consistent Content Feels Calmer",
    "How Structure Removes Decision Fatigue",
    "Why You Don’t Need to Overthink Captions",
    "The Quiet Power of Showing Up Every Week",
    "Why Content Should Work Even When You’re Offline",
    "The Relief of Not Having to Think About What to Post",
    "Why Systems Beat Hustle Every Time",
    "How Consistency Builds Familiarity Over Time",
    "Why Content Burnout Is So Common",
    "The Difference Between Posting Often and Posting Reliably",
    "Why Your Audience Doesn’t Need Perfection",
    "How Visibility Supports Sales Without Pressure",
    "Why Content Should Feel Predictable — In a Good Way",
    "The Cost of Letting Your Page Go Quiet",
    "Why Staying Visible Is Easier With Structure",
    "How Repetition Builds Recognition",
    "Why Posting Weekly Is Enough",
    "The Calm of Knowing Your Content Is Covered",
    "Why Social Media Feels Hard Without a System",
    "How Content Consistency Reduces Stress",
    "Why You Don’t Need to Be a Content Creator",
    "The Freedom of Not Managing Posts Manually",
    "Why Consistency Protects Momentum",
    "How Structure Turns Content Into Background Work",
    "Why Being Remembered Matters More Than Being Clever",
    "The Relief of Removing Content From Your Brain",
    "Why Content Should Support Your Life, Not Compete With It"
];

export async function selectTopic() {
    console.log("Selecting random topic from list...");
    
    // Logic: Select Random Topic
    const randomIndex = Math.floor(Math.random() * topicsList.length);
    const selectedTopic = topicsList[randomIndex];

    return selectedTopic;
}
