// steps/selectTopic.js

// The list of topics (Cleaned: no numbers)
const topicsList = [
    "Confusion as a Control Tool",
    "When Love Feels Conditional",
    "The Slow Erosion of Self Trust",
    "Spiritual Language Used to Silence",
    "Gaslighting Without Obvious Lies",
    "The Cycle of Hope and Disappointment",
    "When Apologies Change Nothing",
    "Kindness With Hidden Costs",
    "Feeling Responsible for Someone Else’s Emotions",
    "Peace That Comes From Giving Up",
    "Why Everything Feels Like Your Fault",
    "The Difference Between Patience and Endurance",
    "Emotional Exhaustion as a Warning Sign",
    "When Boundaries Are Called Selfish",
    "Confusion Mistaken for Complexity",
    "The Role of Shame in Control",
    "Love That Requires Self Betrayal",
    "When Support Comes With Strings",
    "Walking on Eggshells Without Knowing Why",
    "The Loss of Joy You Can’t Explain",
    "How Control Masquerades as Care",
    "The Fear of Speaking Honestly",
    "When Silence Feels Safer Than Truth",
    "Emotional Whiplash in Relationships",
    "The Power of Inconsistency",
    "When Forgiveness Is Weaponized",
    "Trusting Someone Who Keeps Hurting You",
    "The Gradual Shrinking of Your World",
    "Feeling Guilty for Needing Rest",
    "When Empathy Is Exploited",
    "Conflicting Realities in the Same Relationship",
    "How Manipulation Feels Invisible",
    "The Burden of Being the Reason Things Work",
    "When Love Feels Like Management",
    "Self Doubt as a Learned Response",
    "Being Praised and Punished for the Same Trait",
    "The Cost of Constant Self Monitoring",
    "When Intuition Is Labeled Rebellion",
    "Emotional Safety Versus Emotional Intensity",
    "Why Leaving Feels Like Failure",
    "The Trap of Trying Harder",
    "How Narcissistic Cycles Reinforce Attachment",
    "The Difference Between Conviction and Control",
    "When Reality Depends on Someone Else’s Mood",
    "Confusing Loyalty With Love",
    "How Abuse Can Feel Like Purpose",
    "The Role of Fear in Staying",
    "When Spiritual Duty Overrides Self Care",
    "Feeling Invisible While Being Needed",
    "The Subtle Loss of Agency",
    "Why Clarity Often Comes Late",
    "The Cost of Being the Peacemaker",
    "How Isolation Happens Quietly",
    "When Growth Is Treated as a Threat",
    "The Emotional Toll of Uncertainty",
    "How Control Adapts Over Time",
    "Love That Requires Constant Proof",
    "When Accountability Is One Sided",
    "The Impact of Chronic Invalidations",
    "Why You Stop Trusting Your Memory",
    "The Difference Between Strength and Suppression",
    "How Dependency Is Manufactured",
    "When Support Turns Into Surveillance",
    "The Fear of Being Misunderstood",
    "How Emotional Debt Is Created",
    "When Everything Is a Test",
    "The Exhaustion of Explaining Yourself",
    "How Abuse Can Look Like Stability",
    "The Role of Hope in Prolonging Harm",
    "When Compromise Becomes Self Erasure",
    "The Cost of Emotional Overfunctioning",
    "Why You Feel Smaller Over Time",
    "The Confusion of Mixed Messages",
    "When Caretaking Replaces Partnership",
    "How Control Thrives in Ambiguity",
    "The Difference Between Love and Leverage",
    "When Spiritual Authority Overrides Conscience",
    "The Impact of Chronic Fear on Decision Making",
    "How Guilt Is Used to Maintain Power",
    "When Leaving Feels Spiritually Wrong",
    "The Emotional Math That Never Adds Up",
    "Why You Feel Responsible for Their Healing",
    "The Normalization of Emotional Pain",
    "How Abuse Disguises Itself as Growth",
    "The Loss of Spontaneity",
    "When Validation Is Conditional",
    "The Cost of Constant Self Correction",
    "How Fear Replaces Desire",
    "When Being Needed Feels Like Being Loved",
    "The Confusion Between Submission and Surrender",
    "How Reality Becomes Negotiable",
    "The Emotional Weight of Unspoken Rules",
    "When Trust Requires Ignoring Yourself",
    "The Long Term Effects of Emotional Control",
    "Why Boundaries Trigger Backlash",
    "The Difference Between Grace and Tolerance of Harm",
    "How Abuse Trains You to Doubt Clarity",
    "When Love Feels Like Obligation",
    "The Silent Grief of Losing Yourself",
    "How Control Survives Good Intentions",
    "When Healing Feels Disloyal",
    "The Role of Fear in Spiritual Compliance",
    "Why You Feel Relief After Giving In",
    "The Cost of Constant Emotional Readiness",
    "How Power Imbalances Become Normal",
    "When Apologies Replace Change",
    "The Confusion of Being Chosen and Controlled",
    "How Abuse Can Feel Like Identity",
    "The Impact of Emotional Neglect",
    "When Needs Are Framed as Demands",
    "The Subtle Transition From Love to Fear",
    "Why You Feel Guilty for Wanting Peace",
    "The Difference Between Faith and Fear",
    "How Narcissistic Abuse Distorts Love",
    "When Protection Looks Like Restriction",
    "The Cost of Ignoring Red Flags",
    "How Emotional Control Shapes Beliefs",
    "When Obedience Is Framed as Virtue",
    "The Loss of Trust in Your Own Voice",
    "How Abuse Rewrites Reality",
    "When Compassion Is Used Against You",
    "The Emotional Impact of Constant Uncertainty",
    "Why You Feel Afraid to Be Honest",
    "The Difference Between Sacrifice and Self Loss",
    "How Power Hides Behind Kindness",
    "When Healing Threatens the Relationship",
    "The Weight of Being the Stable One",
    "How Emotional Abuse Avoids Detection",
    "When Love Requires Silence",
    "The Cost of Staying Small",
    "How Narcissistic Patterns Escalate",
    "When Growth Is Met With Resistance",
    "The Emotional Confusion of Mixed Affection",
    "Why You Feel Drained After Peace",
    "The Role of Control in Spiritual Abuse",
    "When Support Feels Conditional",
    "How Abuse Redefines Normal",
    "The Fear of Being Seen Clearly",
    "When Hope Delays Freedom",
    "The Difference Between Endurance and Healing",
    "How Emotional Abuse Impacts Faith",
    "When Love Feels Like Survival",
    "The Cost of Constant Accommodation",
    "How Control Feels Like Protection",
    "When Truth Feels Dangerous",
    "The Emotional Toll of Invisible Harm",
    "Why Clarity Can Feel Like Betrayal",
    "The Long Road Back to Self Trust",
    "When Peace Requires Distance",
    "Relearning What Healthy Love Feels Like"
];

export async function selectTopic() {
    console.log("Selecting random topic from list...");
    
    // Logic: Select Random Topic
    const randomIndex = Math.floor(Math.random() * topicsList.length);
    const selectedTopic = topicsList[randomIndex];

    return selectedTopic;
}
